### ISSUE TITLE
[bootstrap] Bootstrap fails because when disk cache has previously mapped the current aws_access_key_id to a AWS Account ID

### ISSUE THREAD

**Issue by Tehnix** [localstack/aws-cdk#4]
Because CDK caches your AWS Account ID if you have previously used CDK on your machine, it will fail to run any operation that ends up using https://github.com/localstack/aws-cdk/blob/master/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts#L224-L240 and relies on a correct AWS Account ID.

The `bootstrap` operation is one of these.

The two cache files CDK uses are:

- `~/.cdk/cache/accounts.json`
- `~/.cdk/cache/accounts_partitions.json`

### Reproduction Steps

1. Deploy a stack to AWS using regular CDK flow and your default AWS profile.
2. Start `localstack`.
3. Run `cdklocal --verbose bootstrap aws://000000000000/eu-west-1` (`000000000000` is the default account id in LocalStack).
4. Bootstrapping process fails with the following:

```
$ cdklocal --verbose bootstrap aws://000000000000/eu-west-1
....
 ⏳  Bootstrapping environment aws://000000000000/eu-west-1...         t
     Environment aws://000000000000/eu-west-1 failed bootstrapping: Error: Need to perform AWS calls for account 000000000000, but the current credentials are for XXXXXXXXXXXX.
    at SdkProvider.obtainCredentials (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/aws-auth/sdk-provider.ts:268:11)
    at SdkProvider.forEnvironment (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/aws-auth/sdk-provider.ts:154:19)
    at Function.lookup (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/bootstrap/deploy-bootstrap.ts:35:17)
    at Bootstrapper.legacyBootstrap (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/bootstrap/bootstrap-environment.ts:60:21)
    at /home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/cdk-toolkit.ts:359:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/cdk-toolkit.ts:356:5)
    at initCommandLine (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/bin/cdk.ts:199:9)
Need to perform AWS calls for account 000000000000, but the current credentials are for XXXXXXXXXXXX.
Error: Need to perform AWS calls for account 000000000000, but the current credentials are for XXXXXXXXXXXX.
    at SdkProvider.obtainCredentials (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/aws-auth/sdk-provider.ts:268:11)
    at SdkProvider.forEnvironment (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/aws-auth/sdk-provider.ts:154:19)
    at Function.lookup (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/bootstrap/deploy-bootstrap.ts:35:17)
    at Bootstrapper.legacyBootstrap (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/api/bootstrap/bootstrap-environment.ts:60:21)
    at /home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/cdk-toolkit.ts:359:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/lib/cdk-toolkit.ts:356:5)
    at initCommandLine (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk-local/bin/cdk.ts:199:9)
```

### What did you expect to happen?

I would expect `cdklocal` to either disable caching, or force it to go via STS which is the fallback.

### What actually happened?

`cdklocal` ends up getting a cached AWS Account ID, which it should *not* use.

### Environment

  - **CLI Version      :** 1.64.1-dev1 (build 2f5afc6)
  - **Framework Version:**
  - **Node.js Version:** 14.12.0 
  - **OS               :** Ubuntu
  - **Language (Version):** TypeScript 4.0.1 

### Other

Current workaround is to make sure the cache files are removed before any run of bootstrap. I've set up my command as `(rm ~/.cdk/cache/accounts.json || true) && (rm ~/.cdk/cache/accounts_partitions.json || true) && cdklocal --verbose bootstrap aws://000000000000/$AWS_REGION` at the moment.

--- 

This is :bug: Bug Report

**Comment by whummer** [comment]
Thanks for the detailed report @Tehnix . Please note that this repo is now deprecated - can you please give it a try with the new implementation here (see Configuration section in the README): https://github.com/localstack/aws-cdk-local Hope that helps - please open a follow-up ticket in the new repo if the problem persists. Thanks for your help!

**Comment by Tehnix** [comment]
@whummer awesome! I'll give it a try :)
